# Default values for adoagent.
replicaCount: 1
label: myapp1

# Image variable
image:
  name: myapp1-container
  repository: mcpatralrepo.azurecr.io
  imageName: webapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0"

# Service variables
service:
  type: NodePort
  port: 80
  nodePort: 31300


