apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }} # ClusterIp, # NodePort 
  selector:
    app: {{ .Values.label }}
  ports: 
    - name: {{ .Release.Name }}-svc
      port: {{ .Values.service.port }} # Service Port
      targetPort: {{ .Values.service.port }} # Container Port
      nodePort: {{ .Values.service.nodePort }} # Node Port